import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Image from "next/image";
import Card from "../components/card.component";
import coffeeStoresData from "../data/coffe-store.json"

export async function getStaticProps(context) {
    console.log(" Hi getStaticProps");
    return {
        props: {
            coffeeStores: coffeeStoresData,
        },
    };
}

export default function Home(props) {
    console.log("props", props);
  const handleOnBtnClick = () => {
      console.log("hi banner button");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby"  handleOnClick={handleOnBtnClick}/>
        <div className={styles.heroImage}>
            <Image src="/static/hero-image.png" width={700} height={400}/>
        </div>
          {props.coffeeStores.length > 0 && (
              <>
                  <h2 className={styles.heading2}>Toronto Coffee Store</h2>
                  <div className={styles.cardLayout}>
                      { props.coffeeStores.map((coffeeStore) => {
                          return(
                              <Card
                              key={coffeeStore.id}
                              name={coffeeStore.name}
                              imgUrl={coffeeStore.imgUrl}
                              href={`/coffee-store/${coffeeStore.id}`}
                              />
                          );
                      })}
                  </div>
              </>
          )}
      </main>
    </div>
  )
}
